sudo: required
dist: xenial
language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libudev-dev
        sonarcloud:
          organization: "gerryferdinandus-github"
      env:
        - COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode10.1
      env:
        - COMPILER=clang++ C_COMPILER=clang BUILD_TYPE=Debug
    - os: windows
      env:
        - COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Debug


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export EXTRA_OPTIONS="-DCMAKE_SH='CMAKE_SH-NOTFOUND'"; fi
  - cd ${TRAVIS_BUILD_DIR}
#  - mkdir -p build && cd build

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${EXTRA_OPTIONS} .; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${EXTRA_OPTIONS} .; fi
  # build-wrapper-linux-x86-64 must be run from the project root
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build-wrapper-linux-x86-64 --out-dir bw-output cmake --build . -- -j2; fi
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then cmake --build . -- -j2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sonar-scanner; fi
