sudo: required
dist: xenial
language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libudev-dev
      env:
        - COMPILER=g++-7 C_COMPILER=gcc-7 BUILD_TYPE=Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libudev-dev
      env:
        - COMPILER=g++-8 C_COMPILER=gcc-8 BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode10
      env:
        - COMPILER=clang++ C_COMPILER=clang BUILD_TYPE=Debug
    - os: windows
      env:
        - COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Debug


before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export EXTRA_OPTIONS="-DCMAKE_SH='CMAKE_SH-NOTFOUND'"; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export CC="C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/gcc.exe"; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export CXX="C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/g++.exe"; fi
- mkdir -p build && cd build

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mingw -y; fi

script:
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${EXTRA_OPTIONS} ..; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${EXTRA_OPTIONS} ..; fi
- cmake --build . -- -j2
