sudo: required
dist: trusty
language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libudev-dev
      env:
        - COMPILER=g++-7 C_COMPILER=gcc-7 BUILD_TYPE=Debug
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
